import base from '@execuneed/config/eslint'

export default [
  // Generated by `next dev` / `next build`; not ours to lint.
  { ignores: ['next-env.d.ts', '.next/**'] },
  ...base,
  {
    files: ['app/**/*.{ts,tsx}', 'src/**/*.{ts,tsx}'],
    languageOptions: {
      globals: { React: 'readonly', process: 'readonly' },
    },
  },
]
